### ISSUE TITLE
paste doesn't work with marks

### ISSUE THREAD

**Issue by BrianHung** [automerge/automerge-prosemirror#18]
Tested with v0.0.13-alpha.3, but bug may have existed before then.

![CleanShot 2024-08-14 at 00 09 08](https://github.com/user-attachments/assets/4db3cdc4-5404-428e-878f-6bbbedcc8146)

I tried debugging this myself but it seems to be a problem inside of `updateSpans`: left is the newSpans, right is the field after update is called. They should be equal.

![CleanShot 2024-08-14 at 00 11 28@2x](https://github.com/user-attachments/assets/d4f7b92b-1985-4df8-b2a2-2cccb97c0cd2)

https://github.com/automerge/automerge-prosemirror/blob/08612db748290d371ae053a7b5831309cd2d65c6/src/pmToAm.ts#L124

**Comment by alexjg** [comment]
The issue here is that [`updateSpans`](https://automerge.org/automerge/api-docs/js/functions/next.updateSpans.html) only updates the block structure and not the marks. This means that the marks for pasted content are lost.

The solution I am working on for this is to update the API of automerge so that `updateSpans` also updates the marks. This is a bit fiddly and it's not at the top of my todo list so I haven't finished it yet. In the meantime the solution is probably to write some code in the prosemirror bindings which performs this reconciliation when it detects a paste.

**Comment by BrianHung** [comment]
No rush! I wonder if we can catch these bugs automatically by comparing the [counterfactual EditorState that is produced by directly applying the transaction](https://github.com/automerge/automerge-prosemirror/blob/08612db748290d371ae053a7b5831309cd2d65c6/src/intercept.ts#L40), against the one produced by applying the transformed-by-automerge transaction. Theoretically, they should be the same with [`Node.eq`](https://prosemirror.net/docs/ref/#model.Node.eq), right?

**Comment by alexjg** [comment]
They should indeed be the same so yes, this would be worth doing. In fact, one future plan I have (which I would love someone else to get around to before me :stuck_out_tongue: ) is to modify the architecture so that instead of intercepting the transaction and creating an entirely new one, we actually apply the transaction directly (i.e. the normal ProseMirror flow) and then convert the transaction into a change to the automerge document. At this point, if we've done our job right the automerge document should be equivalent to the ProseMIrror document but if they aren't then we can add a fixup to the ProseMirror transaction using `appendTransaction`. The very large advantage of this approach is that it transparently works with other ProseMirror plugins (esp. undo).
