### ISSUE TITLE
provide a way to add metadata to transaction made from remote changes

### ISSUE THREAD

**Issue by Ryan-Sheehan** [automerge/automerge-prosemirror#19]
Currently, `reconcilePatch` accepts the incoming patches from Automerge and the current `EditorState` from Prosemirror and returns a new `EditorState` to set. For the case of working with the Prosemirror history plugin, it would be nice to be able to mark the transaction created by the incoming patch with [`tx.setMeta('addToHistory', false)`](https://prosemirror.net/docs/ref/#history) so that only changes made locally are added to the history stack.

**Comment by alexjg** [comment]
I agree that we should do this, however, for it to be useful I think we first need to modify the architecture in the manner I propose [here](https://github.com/automerge/automerge-prosemirror/issues/18#issuecomment-2289998369)  because at the moment we completely replace any incoming transactions which I think will mess up the metadata the history plugin needs (although I could be wrong about that, I haven't tried it).
